## 오늘의 회고 ヾ(•ω•`)o

### 테스트와 리팩토링은 정말 소중해..

<br>

### 느낀 점 😃

어제 기능 구현을 얼추 마무리 짓고, 전체 게임이 실행되는 코드를 작성한 뒤 테스트를 실행했다. 이번에 코드를 짤 때 고민을 많이 해서, 아마도 다 통과하지 않을 까 했는데 둘 다 실패했다(ㅠㅠ). 예외처리는 아마도 다른 방식의 예외처리를 해야할 것 같다는 생각이 들었고 기능 구현은 구글링을 하여 문제를 파악했다. (설명은 아래에)

<br>

### ApplicationTest 중 발생한 error ❌

<br>

1. 기능 구현 테스트가 실행 되지 않았을 때 💩

```(java)
    java.lang.UnsupprotedOperationException 에러
```

제공된 로또 클래스에 숫자를 생성하는 generate 클래스에서 만들어낸 로또 리스트를 넣어줄 때 초기 생성을 하지 않아서 발생한 오류였다. 어떤 리스트를 넣고 싶다면

```(java)
    List<Integer> generateNumber = new ArrayList<>(numbers);
```

이런식으로 리스트 생성하면서 값을 넣어주도록 하자!

<br>

2. 예외 처리 테스트가 제대로 실행 되지 않았을 때 💩

처음에는 지난 주차와 똑같이 if문으로 걸러서 throw문을 사용했는데 왜 테스트가 실패하나 했다.. 그냥 출력하라는 그 한 문장만 다른 줄 알았다..

```(java)
//2주차 미션 요구사항
사용자가 잘못된 값을 입력할 경우 IllegalArgumentException을 발생시킨 후 애플리케이션은 종료되어야 한다.

//3주차 미션 요구사항
사용자가 잘못된 값을 입력할 경우 IllegalArgumentException를 발생시키고, "[ERROR]"로 시작하는 에러 메시지를 출력 후 종료한다.
```

이렇게 두고 보니까 뭔가 다르다는 게 느껴지지 않나?

<br>

맞다. 2주차는 그냥 예외 처리를 시켜주는 것이고 3주차는 예외를 발생키고 throw한 예외 처리를 받아와 에러 메시지를 던지는 것이다..

<br>

그러니까 단순히 throw new IllegalArgumentException을 하면 예외만 발생하겠지!!!

<br>

try, catch문은 try 부분에 예외가 걸릴만한 코드가 있다면 예외가 걸리는 부분에서 catch로 이동해 해당 예외가 발생했을 때 던지는 메시지를 받아와 출력해준다. (나만 헷갈렸을 것 같지만) 당연히 try 아래부분은 예외 발생 시 실행이 되지 않고, try-catch문 바깥의 이후 실행 코드가 있다면 그 부분은 실행된다. 그래서 startGame 메서드에서 try-catch를 작성해 실패하면 바로 게임이 종료되도록 했다!
